# ==================== APPLICATION ====================
spring.application.name=pharmacy.api

# ==================== DATABASE ====================
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_db
spring.datasource.username=root
spring.datasource.password=root

# ==================== JPA ====================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================== FLYWAY ====================
spring.flyway.enabled=true

# ==================== LOGGING ====================
logging.level.com.limasantos.pharmacy=DEBUG
logging.level.org.springframework.web=DEBUG

# ==================== SWAGGER / OPENAPI ====================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=method

api.docs.title=HealthSync API - Sistema de Gest\u00E3o integrada para Farm\u00E1cias e Distribuidoras
api.docs.description=API REST para gerenciamento de vendas, estoque, clientes, fornecedores e financeiro no ecossistema HealthSync.
api.docs.version=1.0.0
api.docs.contact.name=Guilherme Lima
api.docs.contact.email=guilimadev19@gmail.com
api.docs.contact.url=https://github.com/limasantos
api.docs.developer.role=Desenvolvedor Backend
api.docs.project.url=https://github.com/limasantos/healthsync

# ==================== CORS ====================
api.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# ==================== jwtoken ====================
api.security.token.secret=${JWT_SECRET:mysecretkey}